# Generated by Django 6.0.6 on 2026-06-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic Writing'), ('seo', 'SEO Writing'), ('copywriting', 'Copywriting'), ('business', 'Business Reports'), ('creative', 'Creative Writing'), ('ghostwriting', 'Ghostwriting'), ('cv', 'CV Writing'), ('blogging', 'Blogging')], max_length=20)),
                ('instructions', models.TextField()),
                ('word_count', models.IntegerField()),
                ('pay_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='open', max_length=10)),
                ('visibility', models.CharField(choices=[('all', 'All Tiers'), ('standard', 'Standard & Premium'), ('premium', 'Premium Only')], default='all', max_length=10)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='job_refs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', max_length=25)),
                ('admin_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='work.job')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
