# Generated by Django 6.0.6 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='reference',
        ),
        migrations.AddField(
            model_name='earning',
            name='commission_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='earning',
            name='gross_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='earning',
            name='net_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='mpesa_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
